# Generated by Django 5.1.7 on 2025-04-23 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0002_backgroundimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='background',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routes.backgroundimage'),
        ),
    ]
