# Generated by Django 5.1.7 on 2025-05-16 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0005_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='path',
            name='name',
            field=models.CharField(default='Unnamed Path', max_length=100),
        ),
    ]
